SET Game_Motive  = "Integrated with Learning"
SET Game_Effect  = "Integrated with Learning"
SET Game_Content = "Integrated with Learning"
SET Game_Content = "Integrated with Learning"
SET Game_Order   = "Integrated with Learning"
SET Game_Role    = "Integrated with Learning"
SET Game_Rules   = "Integrated with Learning"
SET Game_Goals   = "Integrated with Learning"
